.github/workflows/docker-image.yml
This automatically generates docker images from the repository and publishes them to the github container registry. The `main` branch is tagged with `:edge` and when you push git tags it tags those as `:v1.2.3` and `:latest`.
I ran the action in my fork and it now looks like this:
=> Add github actions for docker

Dockerfile
Fixes #18
Added stage to Dockerfile for fetching and building Rust dependencies based on project's Cargo files. Creates stub files to facilitate build then in following stage copies full project and updates file timestamps to cause a compile on the actual project. Once the build is cached subsequent code changes will only impact the project's build stage. It's a little clunky, but unfortunately Cargo currently does not have a "fetch / build dependencies only" command.
Tested on my fork with CI builds. Initial Docker CI build takes ~15 minutes then subsequent build with 1 line code change took ~2 minutes.
Misc. comment: Could consider using a distroless image such as gcr.io/distroless/cc-debian11 in place of debian:11-slim for a smaller final run-time image.
=> Cache Rust dependencies

docs/RULES.md
=> Fix typos!

CHANGELOG.md, Cargo.lock, Cargo.toml, src/bin/noseyparker/args.rs, src/bin/noseyparker/cmd_github.rs, src/bin/noseyparker/cmd_report.rs, src/bin/noseyparker/cmd_scan.rs, src/bin/noseyparker/cmd_summarize.rs, tests/snapshots/test_noseyparker_help__help_report-2.snap, tests/snapshots/test_noseyparker_help__help_report_short-2.snap, tests/snapshots/test_noseyparker_help__help_summarize-2.snap, tests/snapshots/test_noseyparker_help__help_summarize_short-2.snap, tests/test_noseyparker_scan.rs
Fixes #4 
Hello :wave: 
https://github.com/microsoft/sarif-tutorials/
For this PR I used the crate `serde-sarif`.
Documentation available here : https://docs.rs/serde-sarif/latest/serde_sarif/
And I took inspiration from [this code](https://github.com/flatt-security/shisho/blob/322f1111382b0d6556e11d3fe99bb3195c7ee2d7/src/cli/reporter/sarif.rs).
Here is my PR. Feel free to tell me where I may have done something wrong! It is the first time that I try to contribute to another project. :smile: 
I tested on several report and everything should work. 
The `sarif_format` function in `cmd_report.rs` is quite long. Is it an issue? Should I dispatch in multiple functions or not? 
- **Add commits details :**  If in the future commits details will be added to blob match, I will add them. Linked to …
=> Add SARIF output format for report #4

CHANGELOG.md, Cargo.lock, crates/noseyparker-cli/Cargo.toml, crates/noseyparker-cli/src/bin/noseyparker/args.rs, crates/noseyparker-cli/src/bin/noseyparker/cmd_github.rs, crates/noseyparker-cli/src/bin/noseyparker/cmd_scan.rs, crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_github-2.snap, crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_github_short-2.snap, crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_scan-2.snap, crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_scan_short-2.snap, crates/noseyparker/src/github.rs, crates/noseyparker/src/github/client.rs, crates/noseyparker/src/github/error.rs
This PR adds support for a custom GitHub API url argument for both the scan and github commands. This allows NP to support GitHub Enterprise Server (by passing `https://GHESURL/api/v3/` as the custom API url).
=> Add support for custom GitHub API urls (for GHES support)

CHANGELOG.md, README.md, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_check_builtins-2.snap, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_json-2.snap, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_noargs-2.snap, crates/noseyparker/data/default/builtin/rules/dependency_track.yml, crates/noseyparker/data/default/builtin/rulesets/np.default.yml
Dependency-Track identifies vulnerabilities using a project's Bill of Materials. DTrack has included `odt_ ` as the prefix for tokens in their [default configuration](https://docs.dependencytrack.org/getting-started/configuration/). DTrack is based on Alpine which the API Key (not including the prefix) can be [between 32 and 255 characters long](https://github.com/stevespringett/Alpine/blob/master/alpine-model/src/main/java/alpine/model/ApiKey.java).
=> Added Dependency Track rule

CHANGELOG.md, README.md, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_check_builtins-2.snap, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_json-2.snap, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_noargs-2.snap, crates/noseyparker/data/default/builtin/rules/wireguard.yml, crates/noseyparker/data/default/builtin/rulesets/default.yml
This is a rule I regularly use to look for WireGuard .conf files (specifically private and preshared WG keys). Maybe it makes sense to add it to the defaults. I generated the 2 keys in the example myself just for this purpose.
=> Add WireGuard PrivateKey/PresharedKey rule

CHANGELOG.md, README.md
This is a follow-up of #104 where WireGuard rules have been added but I forgot to update the README and CHANGELOG after splitting the rules.
=> Update rules in README and CHANGELOG

crates/noseyparker/data/default/builtin/rules/wireguard.yml
This is another follow-up to #104 where WireGuard rules were added. But it seems I accidentally removed an `=` from the regex pattern while splitting the rules. Now it is fixed and the pattern is more strict.
=> Fix WireGuard Private Key pattern

crates/noseyparker/data/default/builtin/rules/dockerhub.yml
`-` could be the last character here also, so I updated the pattern similarly to https://github.com/praetorian-inc/noseyparker/pull/108#discussion_r1431708161.
=> Fix Docker Hub Personal Access Token rule

CHANGELOG.md, README.md, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_check_builtins-2.snap, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_json-2.snap, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_noargs-2.snap, crates/noseyparker/data/default/builtin/rules/doppler.yml, crates/noseyparker/data/default/builtin/rulesets/default.yml
I was surprised this is not already included in the default rules, as it is a direct copy-paste from [doppler.com](https://docs.doppler.com/reference/auth-token-formats), lol
=> Add Doppler rules

CHANGELOG.md, README.md, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_check_builtins-2.snap, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_json-2.snap, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_noargs-2.snap, crates/noseyparker/data/default/builtin/rules/particle.io.yml, crates/noseyparker/data/default/builtin/rulesets/default.yml
Added some rules I successfully used to detect particle.io access tokens in the wild. The rules do not contain any patterns to match device IDs because once we have the access tokens, we can retrieve the device list with `curl "https://api.particle.io/v1/devices?access_token=38bb7b318cc6898c80317decb34525844bc9db55"`.
I created two patterns that could be merged into one but this way they are more readable.
=> Add particle.io rules

CHANGELOG.md, README.md, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_check_builtins-2.snap, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_json-2.snap, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_noargs-2.snap, crates/noseyparker/data/default/builtin/rules/adafruitio.yml, crates/noseyparker/data/default/builtin/rulesets/default.yml
Added Adafruit IO key rule. Based on the [API docs](https://io.adafruit.com/api/docs) it is not immediately obvious that the keys have an `aio_` prefix but they do. I verified this:
=> Add Adafruit IO Key rule

CHANGELOG.md, crates/noseyparker-cli/src/args.rs, crates/noseyparker-cli/src/cmd_github.rs, crates/noseyparker-cli/src/cmd_scan.rs, crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_scan-2.snap, crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_scan_short-2.snap, crates/noseyparker/src/git_binary.rs, crates/noseyparker/src/github.rs, crates/noseyparker/src/github/client_builder.rs
This PR closes #116. If there's a need for tests or anything else, I can add them.
There are two approaches I see to CLI arguments:
1. (implemented right now) For each command that interacts with certificates, add an argument to its defined arguments and pass it to the functions. It's more local, closer to actual use, yet adds more places where it needs to be maintained.
2. Consider this to be a global argument. The plus of this approach is that there is only one place for the user to set it, and it could be easily used if additional clients were to be added in the future (e.g. GitLab or something else). The disadvantage is that it would require more modification to the code as `GlobalArgs` is not always passed that deep. Also, it wouldn't apply to all subcommands, so it wouldn't be truly …
=> Allow to ignore validation of TLS certificates

Cargo.lock, crates/bstring-serde/Cargo.toml, crates/bstring-serde/src/lib.rs, crates/input-enumerator/Cargo.toml, crates/input-enumerator/src/git_commit_metadata.rs, crates/noseyparker-cli/Cargo.toml, crates/noseyparker-cli/src/args.rs, crates/noseyparker-cli/src/cmd_json_schema.rs, crates/noseyparker-cli/src/cmd_report.rs, crates/noseyparker-cli/src/main.rs, crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help-2.snap, crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_short-2.snap, crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__no_args-3.snap, crates/noseyparker/Cargo.toml, crates/noseyparker/src/blob_id.rs, crates/noseyparker/src/blob_metadata.rs, crates/noseyparker/src/datastore.rs, crates/noseyparker/src/location.rs, crates/noseyparker/src/match_type.rs, crates/noseyparker/src/provenance.rs, crates/noseyparker/src/provenance_set.rs, crates/noseyparker/src/snippet.rs, scripts/create-release.zsh, share/noseyparker/report-schema.v0.17.json
This adds a JSON Schema for Nosey Parker's JSON report format. This is implemented using the `schemars` crate to mostly automatically generate the schema from Rust data types.
The schema generation mechanism is accessed using a new `json-schema` top-level command, which is hidden from help. This prints the generated schema to stdout.
The generated schema is included in the release builds.
Fixes #72.
=> Add JSON Schema support via schemars

scripts/create-release.zsh
Hi there.
While fixing up the Arch User Repo install script (https://aur.archlinux.org/packages/noseyparker) that I maintain for noseyparker today I noticed there is a likely typo in the shell-completion step of the build script.
The script iterates over several shells, but the call to `noseyparker shell-completion` in there is always done with `--shell zsh` so the completion files would be identical I imagine.
This pull request is a simple fix for that.
Best regards,
Mark.
=> Fix shell-completion line in release build script

.pre-commit-config.yaml, README.md, crates/noseyparker/data/default/builtin/rules/blynk.yml, crates/noseyparker/data/default/builtin/rules/dropbox.yml, crates/noseyparker/data/default/builtin/rules/shopify.yml, crates/noseyparker/data/default/builtin/rules/thingsboard.yml
This adds configuration for [pre-commit](https://pre-commit.com/).
A number of default checks are enabled, and two Rust-specific checks.
=> Add pre-commit support

crates/noseyparker-cli/Cargo.toml, crates/vectorscan-sys/Cargo.toml, crates/vectorscan-sys/build.rs, crates/vectorscan/Cargo.toml
The two new features in the `vectorscan` and `vectorscan-sys` crates are `native_cpu` and `simd_specialization`.  These both produce non-portable binaries, as they depend on microarchitectural details of the build system's CPU.
A third convenience feature, `fast_nonportable`, is also included.
These features are plumbed through to the `noseyparker-cli` crate as `vectorscan_native_cpu`, `vectorscan_simd_specialization`, and `vectorscan_fast_nonportable`, and are all disabled by default.
=> Add performance-related Vectorscan features

CHANGELOG.md, README.md, crates/noseyparker-cli/src/args.rs, crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_report-2.snap
SARIF reporting capabilities have been present in Nosey Parker for a while (#33). However, it is not an output format that has been tested very thoroughly. Its current implementation has some known deficiencies (#34).
Additionally, it seems like the SARIF format [has troubles](https://github.com/oasis-tcs/sarif-spec/issues/564) representing findings from tools like Nosey Parker, which look deep in Git history.
This change explicitly notes that SARIF format is "experimental" in Nosey Parker.
=> Mark SARIF support as experimental

Dockerfile, scripts/create-release.zsh
I got annoyed by how long Docker CI takes, so I thought of ways to speed it up. I realized the biggest issue is that all previous work by the compiler (downloading dependencies, compiling dependencies, compiling crates) is thrown away whenever the source code is modified. This PR is an attempt to fix that up by splitting that work into multiple stages in Dockerfile and utilizing the [`cargo-chef`](https://crates.io/crates/cargo-chef) and GitHub Actions Docker layers cache.
**Note**: The PR so far contains only working improvements for the Debian Dockerfile. The same change in Alpine requires a different approach, and I'm still working on it.
1. Creation of `chef` image with installed `cargo-chef` - should be a one-time thing that gets cached and never repeated
2. Creation of `planner` …
=> Speed up Docker image creation

CHANGELOG.md, crates/noseyparker-cli/src/args.rs, crates/noseyparker-cli/src/cmd_report.rs, crates/noseyparker-cli/src/cmd_report/human_format.rs, crates/noseyparker-cli/src/cmd_report/sarif_format.rs, crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_report-2.snap, crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_report_short-2.snap, crates/noseyparker-cli/tests/report/mod.rs, crates/noseyparker-cli/tests/report/snapshots/test_noseyparker__report__report_nonexistent_default_datastore-2.snap, crates/noseyparker-cli/tests/report/snapshots/test_noseyparker__report__report_nonexistent_default_datastore-3.snap, crates/noseyparker-cli/tests/report/snapshots/test_noseyparker__report__report_nonexistent_default_datastore.snap, crates/noseyparker-cli/tests/report/snapshots/test_noseyparker__report__report_output_colors1.snap, crates/noseyparker-cli/tests/report/snapshots/test_noseyparker__report__report_unlimited_matches-2.snap, crates/noseyparker-cli/tests/report/snapshots/test_noseyparker__report__report_unlimited_matches-3.snap, crates/noseyparker-cli/tests/report/snapshots/test_noseyparker__report__report_unlimited_matches.snap, crates/noseyparker-cli/tests/scan/basic/mod.rs, crates/noseyparker-cli/tests/scan/basic/snapshots/test_noseyparker__scan__basic__report_nonexistent_default_datastore-2.snap, crates/noseyparker-cli/tests/scan/basic/snapshots/test_noseyparker__scan__basic__report_nonexistent_default_datastore.snap, crates/noseyparker-cli/tests/scan/basic/snapshots/test_noseyparker__scan__basic__report_unlimited_matches-3.snap, crates/noseyparker-cli/tests/scan/basic/snapshots/test_noseyparker__scan__basic__report_unlimited_matches.snap, crates/noseyparker-cli/tests/test_noseyparker.rs
This allows a user to include only findings with a particular assigned status when running `report`.
=> `report`: add `--finding-status=STATUS` filter

.github/workflows/docker-image.yml
By default, `docker/build-push-action` uses `buildkit` as a scope. In our Docker CI setup, we're building two images at the same time, and it seems that those caches were somehow overwritten in a way that they couldn't be reused. By setting the custom scope, the caching started working. In tests in my personal repo, the building time of the Debian image (one designed to use that caching well) went down from 9m 48s to 5m 41s.
=> Set custom scope for Docker build CI

.github/workflows/ci.yml
This might be helpful at tracking down SIGILL crashes I have seen sporadically and recently.
=> CI: add a step to print build system CPU info

Cargo.lock, crates/noseyparker-cli/Cargo.toml, crates/noseyparker-cli/src/cmd_scan.rs, crates/noseyparker-cli/src/main.rs
This enables colored panic backtraces by default, using the [colored-backtrace](https://crates.io/crates/color-backtrace) crate. This color-codes stack frames by runtime code / library code / user code, includes source snippets, and is overall more legible than default backtraces.
This new support is behind the new `colored_backtrace` feature flag, which is enabled by default.
Also in this: make the `tracing` spans produced when scanning more useful.
=> Add support for colored backtraces; make tracing spans more useful

CHANGELOG.md, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_check_builtins-2.snap, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_json-2.snap, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_noargs-2.snap, crates/noseyparker/data/default/builtin/rules/databricks.yml, crates/noseyparker/data/default/builtin/rulesets/default.yml
Adding a rule for Databricks Personal Access Token detection and enabling it in the default ruleset.
=> Adding a rule for Databricks Personal Access Token detection

crates/noseyparker/src/git_binary.rs
This small PR modifies the git credential helper to pass the PAT stored in the `$NP_GITHUB_TOKEN` env variable as the git password field rather than the username. In my testing, this change makes it possible to clone private GitLab repos with the `--git-url` argument as long as the GitLab PAT is set in the `$NP_GITHUB_TOKEN` env variable.
My testing also shows that cloning private GitHub repos with the `--git-url` argument still works as expected after this change.
=> General support - PATs in git password field

CHANGELOG.md, crates/noseyparker-cli/src/args.rs, crates/noseyparker-cli/src/cmd_scan.rs, crates/noseyparker-cli/src/cmd_summarize.rs, crates/noseyparker-cli/tests/datastore/snapshots/test_noseyparker__datastore__export_empty-2.snap, crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_summarize-2.snap, crates/noseyparker-cli/tests/scan/appmaker/snapshots/test_noseyparker__scan__appmaker__scan_workflow_from_git_url-2.snap, crates/noseyparker-cli/tests/scan/basic/snapshots/test_noseyparker__scan__basic__scan_secrets1-2.snap, crates/noseyparker-cli/tests/scan/snippet_length/snapshots/test_noseyparker__scan__snippet_length__scan_changing_snippet_length-2.snap, crates/noseyparker-cli/tests/scan/snippet_length/snapshots/test_noseyparker__scan__snippet_length__scan_changing_snippet_length-9.snap, crates/noseyparker/src/datastore.rs, crates/noseyparker/src/datastore/finding_summary.rs
- Add columns for status labels
- Improve error handling of summary-producing operations (these should not ever fail under normal circumstances, so give a stack trace when they do)
- Add more detailed command-level help to `summarize --help`
=> Improve `summarize`

.github/workflows/ci.yml, .github/workflows/release-artifacts.yml
GitHub Actions now offers ARM64-based hosted runners in public beta:
- https://github.blog/changelog/2024-06-03-actions-arm-based-linux-and-windows-runners-are-now-in-public-beta/
- https://github.blog/changelog/2024-06-24-github-actions-ubuntu-24-04-image-now-available-for-arm64-runners/
We've set up two ARM64-flavored runners at Praetorian: `ubuntu-22.04` and an `ubuntu-24.04`.
This change uses those runners for CI and release builds as additional targets.
=> Use new Linux arm64 runners in CI

CHANGELOG.md, crates/noseyparker-cli/src/args.rs
The v0.18.0 release crashes upon startup when running in an environment with less that 4GiB of RAM. The crash is an assertion failure from the `std::cmp::Ord::clamp` function when it is called with invalid arguments (i.e., `min > max`).
This crashing behavior was introduced in #174.
=> Fix startup assertion failure on <4GiB RAM machines

CHANGELOG.md, crates/noseyparker-cli/src/args.rs, crates/noseyparker-cli/src/cmd_github.rs, crates/noseyparker-cli/src/cmd_scan.rs, crates/noseyparker-cli/tests/common/mod.rs, crates/noseyparker-cli/tests/datastore/mod.rs, crates/noseyparker-cli/tests/github/mod.rs, crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_scan-2.snap, crates/noseyparker-cli/tests/help/snapshots/test_noseyparker__help__help_scan_short-2.snap, crates/noseyparker-cli/tests/report/mod.rs, crates/noseyparker-cli/tests/scan/basic/mod.rs, crates/noseyparker/src/github.rs, crates/noseyparker/src/github/repo_enumerator.rs
The `scan` and `github repos list` commands offer a new `--github-repo-type={all,source,fork}` option to select a subset of repositories. The default value is `source`, which causes all forked repos on GitHub to be ignored.
=> Add a mechanism to filter out GitHub forks

CHANGELOG.md, Dockerfile.alpine
=> Update Alpine image from `3.18` to `latest`

Cargo.lock, crates/noseyparker-cli/Cargo.toml
Previously, the version had been pinned to an older one because recent mimalloc changes broke the build on some platforms.
=> Update mimalloc dependency

.github/workflows/docker-image.yml, .github/workflows/release-artifacts.yml
This overhauls how the Docker images get built in GitHub Actions.
Previously, only x86_64 Docker images were being built for non-release commits, as using QEMU to build multiplatform images for arm64 as well takes a very long time.
Now, with these changes, the GitHub Actions workflow that builds the Docker images builds for x86_64 and arm64 as separate jobs on native CPU runners, and then merges the individual images together.
This was adapted from the example on the [Docker documentation site](https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners).
Fixes #156.
Fixes #91.
=> Overhaul Docker CI builder

Cargo.lock, crates/input-enumerator/src/git_repo_enumerator.rs, crates/input-enumerator/src/lib.rs, crates/noseyparker-cli/Cargo.toml, crates/noseyparker-cli/src/cmd_scan.rs, crates/noseyparker-cli/tests/scan/with_ignore/mod.rs
- The `FilesystemEnumerator` type now _only_ enumerates directories and files, and as such is a relatively lightweight task.
- Heavyweight enumeration tasks, including walking through Git history and extensible enumerator output (i.e., from the `--enumerator=FILE` option) are now performed by scanner threads instead of filesystem enumerator threads.
- Git repositories are now opened just a single time instead of twice.
- A new `ParallelBlobIterator` trait codifies things that can be enumerated to produce blobs with provenance metadata. This includes for now Git repositories, regular files, extensible enumerators. This starts to put in place necessary pieces to allow for enumeration of tarfiles, compressed archives, etc.
- Large parts of the `scan` command logic are now extracted into …
=> Rework parallelism in enumeration and scanning

CHANGELOG.md, crates/input-enumerator/src/blob_appearance.rs, crates/input-enumerator/src/bstring_table.rs, crates/input-enumerator/src/git_metadata_graph.rs, crates/input-enumerator/src/git_repo_enumerator.rs, crates/input-enumerator/src/lib.rs, crates/noseyparker-cli/src/args.rs, crates/noseyparker-cli/src/cmd_report/sarif_format.rs, crates/noseyparker-cli/src/cmd_scan.rs, crates/noseyparker/Cargo.toml, crates/noseyparker/src/provenance.rs, crates/noseyparker/src/provenance_set.rs
Rework git metadata calculation to reduce peak memory and wall clock time when scanning. This includes many changes.  The net effect of all this is a typical 30% speedup and 50% memory reduction when scanning Git repositories; in pathological cases, up to 5x speedup and 20x memory reduction.
- Git metadata graph:
- Do not construct in-memory graph of all trees and blob names; instead, read tree objects from repo as late as possible
- Use `SmallVec` to reduce heap fragmentation and small heap allocations
- Use more suitable initial size for worklists and scratch buffers to reduce reallocations and heap fragmentation
- Use the fastest / slimmest order for iterating object headers from a git repository when initially counting objects
- Eliminate redundant intermediate data structures; remove …
=> Reduce memory and CPU use when scanning

.github/workflows/docker-image.yml, .github/workflows/release-artifacts.yml
The approach for building statically-linked releases is to build the Alpine-based Docker image, then copy the resulting release out of there.
Fixes #177.
=> Add a release artifacts job for statically-linked Linux releases

CHANGELOG.md, Cargo.lock, crates/noseyparker-cli/tests/generate/snapshots/test_noseyparker__generate__generate_json_schema.snap, crates/noseyparker-cli/tests/scan/basic/mod.rs, crates/noseyparker-cli/tests/scan/basic/snapshots/test_noseyparker__scan__basic__scan_enumerator_base64_1-7.snap, crates/noseyparker-cli/tests/scan/basic/snapshots/test_noseyparker__scan__basic__scan_enumerator_string_provenance-2.snap, crates/noseyparker-cli/tests/scan/basic/snapshots/test_noseyparker__scan__basic__scan_enumerator_string_provenance-3.snap, crates/noseyparker-cli/tests/scan/basic/snapshots/test_noseyparker__scan__basic__scan_enumerator_string_provenance-4.snap, crates/noseyparker-cli/tests/scan/basic/snapshots/test_noseyparker__scan__basic__scan_enumerator_string_provenance-5.snap, crates/noseyparker-cli/tests/scan/basic/snapshots/test_noseyparker__scan__basic__scan_enumerator_string_provenance-6.snap, crates/noseyparker-cli/tests/scan/basic/snapshots/test_noseyparker__scan__basic__scan_enumerator_string_provenance-7.snap, crates/noseyparker-cli/tests/scan/basic/snapshots/test_noseyparker__scan__basic__scan_enumerator_string_provenance.snap, crates/noseyparker/Cargo.toml, crates/noseyparker/src/provenance.rs
Fix a bug in v0.20.0 where provenance entries from an extensible enumerator could _only_ be JSON objects, instead of arbitrary JSON values as claimed by the documentation.
This requires changing the JSON-format report schema slightly.
=> Fix crash when non-object JSON values are used for enumerator provenance

CHANGELOG.md, README.md, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_check_builtins-2.snap, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_json-2.snap, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_noargs-2.snap, crates/noseyparker/data/default/builtin/rules/anthropic.yml, crates/noseyparker/data/default/builtin/rules/gitalk.yml, crates/noseyparker/data/default/builtin/rulesets/default.yml
Add two new rules:
- `Anthropic API Key`
- `Gitalk OAuth Credentials`
=> Add more rules

CHANGELOG.md, README.md, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_check_builtins-2.snap, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_json-2.snap, crates/noseyparker-cli/tests/rules/snapshots/test_noseyparker__rules__rules_list_noargs-2.snap, crates/noseyparker/data/default/builtin/rules/sourcegraph.yml, crates/noseyparker/data/default/builtin/rulesets/default.yml
Added sourcegraph access token rule and tested it locally. Happy to make changes if any.
```bash
running 6 tests
test rules::rules_list_no_builtins ... ok
test rules::rules_list_jsonl ... ok
test help::help_rules ... ok
test rules::rules_list_noargs ... ok
test rules::rules_list_json ... ok
test rules::rules_check_builtins ... ok
test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 78 filtered out; finished in 2.77s
```
=> feature(rule): Added new rule for detecting sourcegraph access token

.github/workflows/ci.yml, .github/workflows/release-artifacts.yml
GitHub Actions has retired the Ubuntu 20.04 runners.
=> Switch from Ubuntu 20.04 to 22.04
